### Numpy

파이썬의 과학 계산용 패키지 <br>
Matrix 와 Vector 와 같은 Array 연산의 사실상의 표준 <br><br>

numpy 는 np.array 함수를 활용하여 배열을 생성 => ndarray <br>
numpy는 하나의 data type 만 배열에 넣을 수 있음 (c의 array를 이용한 배열의 생성, C의 data type과 compatible) <br>
python의 array에 비해서 속도가 빠르다는 장점 <br> <br>

** shape : numpy array의 object의 dimension 구성을 반환함 <br>
** dtype : numpy array의 데이터 type을 반환함 <br><br> 

** ndim : number of dimension <br> 
** size : data의 갯수 

In [1]:
import numpy as np 

In [16]:
test_array = np.array(["1", "4", 5, 8], float)
test_array02 = np.array(["1", "4", 5, 8], np.int32)
# 특정 바이트 크기 지정해야되는 상황이면 np. 붙혀야된다. 
print (test_array)
print (test_array02)

[1. 4. 5. 8.]
[1 4 5 8]


일부는 문자열 타입, 일부는 정수타입으로 지정했으나 전부 float 으로 저장을 해라 했더니 다음과 같이 결과가 도출됨 

In [11]:
print(test_array.dtype)  # Array(배열) 전체의 데이터 Type을 반환함

float64


In [17]:
test_array.shape  # Array(배열)의 shape을 반환함

(4,)

1차원 + 내장돼있는 벡터가 총 4개라는 뜻 <br>
test_array 의 메트릭스 형태가 찍혀나옴 (shape 하면)<br>

In [18]:
tensor = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
] 
# 3차원 배열 

In [21]:
# 차원 수 확인
num_dimensions = np.array(tensor, int).ndim
num_dimensions

3

In [22]:
# 데이터 개수 확인
size = np.array(tensor, int).size
size

64

In [25]:
# Data type을 integer로 선언
arr_int = np.array([[1, 2, 3], [4.5, 5, 6]], dtype=int)
arr_int

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr_float = np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float32)
arr_float

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)