** vector 가 여러개 생기면 matrix <br>

### function

#### 1. creation function 
arange : array의 범위를 지정하여, 값의 list를 생성하는 명령어 <br>
ones, zero, empty : ~~ 로 채워지는 <br>
identity : 단위행렬 (i 행렬) 을 생성함 <br>
eye : 대각선이 1인 행렬, k값의 시작 index 변경이 가능 <br>
diag : 대각 행렬의 값을 주출함

#### 2. operation function
sum : ndarray의 element들 간의 합을 구함, list의 sum 기능과 동일 <br>
axis : 모든 operation function을 실행할 때, 기준이 되는 dimension 축 <br>
concatenate 하는법
* vstack : 수직병합
* hstack : 수평병합 

In [1]:
import numpy as np

In [2]:
np.arange(30)  # range: List의 range와 같은 효과, integer로 0부터 29까지 배열 추출

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
np.arange(0, 5, 0.5)  # (시작, 끝, step) 
# floating point도 표시 가능함, list에서는 이거 지원 X

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [4]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [7]:
np.zeros(shape=(2,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [9]:
test_matrix = np.arange(30).reshape(5,2,3)
np.ones_like (test_matrix)
# 기존 shape 유지하되, 전부 1로 채워짐 

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [10]:
np.identity(n=3, dtype=np.int8) 

## 3 by 3 단위행렬 잘 생성되는거 확인가능

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [11]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
# 대각선이 1인 행렬 생성, k값의 시작 index 변경 가능
np.eye(N=3, M=5, dtype=np.int8) 
# 3행 5열 


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [15]:
np.eye(3)
# 3 by 3 으로 대각선이 1인 행렬 생성됨

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.eye(3,5,k=2) # k => start index 

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
# 대각선의 값만 추출
np.diag(matrix)

array([0, 4, 8])

In [21]:
np.diag(matrix, k=1)
# k는 역시 start index index가 1인 열 1행부터 대각선으로 쭉 뽑힘 

array([1, 5])

In [22]:
# 균등분포에서 샘플링하여 배열 생성
# np.random.uniform(low, high, size)
# low: 최소값, high: 최대값, size: 샘플링할 수 (여기선 10개를 샘플링)
# 0과 1 사이에서 균등하게 분포된 10개의 샘플을 뽑고, 이를 2x5 행렬로 reshape
np.random.uniform(0, 1, 10).reshape(2, 5)


array([[0.76767563, 0.17156434, 0.4915916 , 0.45472365, 0.17144026],
       [0.91065802, 0.78069583, 0.98984141, 0.39808943, 0.68306   ]])

In [23]:
# 정규분포에서 샘플링하여 배열 생성
# np.random.normal(loc, scale, size)
# loc: 평균 (여기선 0), scale: 표준편차 (여기선 1), size: 샘플링할 수 (여기선 10개)
# 평균이 0이고 표준편차가 1인 정규분포에서 10개의 샘플을 뽑고, 이를 2x5 행렬로 reshape
np.random.normal(0, 1, 10).reshape(2, 5)

array([[ 0.78882657, -0.33829973,  1.58724822, -0.17467004,  0.70453401],
       [ 0.7206988 ,  0.64380638, -1.13065795,  0.87143186,  0.24596654]])

In [24]:
# 1부터 12까지의 숫자를 포함하는 배열을 생성하고, 이를 (3,4) 형태로 reshape
test_array = np.arange(1, 13).reshape(3, 4)
print (test_array) 

# axis=1로 sum을 계산 -> 각 row의 합을 계산 (가로로 더하기)
print (test_array.sum(axis=1)) 

# axis=0으로 sum을 계산 -> 각 column의 합을 계산 (세로로 더하기)
print (test_array.sum(axis=0)) 


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[15 18 21 24]


3차원 배열일때 ...

In [25]:
# 1부터 12까지의 숫자를 포함하는 배열을 생성하고, 이를 (3, 4) 형태로 reshape
# 그런 후, 동일한 2D 배열을 3개 쌓아서 3차원 배열을 생성
third_order_tensor = np.array([np.arange(1, 13).reshape(3, 4)] * 3)
print (third_order_tensor) 

# axis=2로 sum을 계산 -> 각 row의 element들끼리 더한 값 (세로 방향)
print (third_order_tensor.sum(axis=2)) 

# axis=1로 sum을 계산 -> 각 matrix의 각 열(column)을 더한 값 (열 방향)
print (third_order_tensor.sum(axis=1)) 

# axis=0으로 sum을 계산 -> 동일한 위치의 element들끼리 더한 값 (층 방향)
print (third_order_tensor.sum(axis=0)) 


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
[[10 26 42]
 [10 26 42]
 [10 26 42]]
[[15 18 21 24]
 [15 18 21 24]
 [15 18 21 24]]
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]


In [27]:
# 1부터 12까지의 숫자를 포함하는 배열을 생성하고, 이를 (3,4) 형태로 reshape
test_array = np.arange(1, 13).reshape(3, 4)
print (test_array) 
# 전체 배열의 평균을 계산
print (test_array.mean())

# axis=0으로 평균 계산 -> 각 열(column)의 평균을 계산
print(test_array.mean(axis=0))

# 전체 배열의 표준 편차를 계산
print (test_array.std())

# axis=0으로 표준 편차 계산 -> 각 열(column)의 표준 편차를 계산
print (test_array.std(axis=0)) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
6.5
[5. 6. 7. 8.]
3.452052529534663
[3.26598632 3.26598632 3.26598632 3.26598632]


In [28]:
a = np.array ([1,2,3])
b = np.array ([2,3,4])
np.vstack ((a,b)) # 수직 병합 

array([[1, 2, 3],
       [2, 3, 4]])

In [31]:
a = np.array ([[1],[2],[3]])
b = np.array ([[2],[3],[4]])
np.hstack ((a,b)) # 수평병합 

# 나중에 재사용하려면 할당 필수 !
# 원본이 바뀌는게 아님 

array([[1, 2],
       [2, 3],
       [3, 4]])

In [32]:
# 두 배열을 생성
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])

# axis=0으로 concatenate -> 세로로 배열 연결 (행 추가)
matrix = np.concatenate((a, b), axis=0)
print (matrix)

# 새로운 두 배열을 생성
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# axis=1로 concatenate -> 가로로 배열 연결 (열 추가)
# 여기서 b.T는 배열 b의transpose로, b의 모양을 (2,1)에서 (1,2)로 변환하여 가로로 연결할 수 있게 한다.
matrix02 = np.concatenate((a, b.T), axis=1)
print (matrix02)


[[1 2 3]
 [2 3 4]]
[[1 2 5]
 [3 4 6]]
