** dtype vs astype <br>
dtype은 **배열을 생성할 때**, 각 요소가 어떤 데이터 타입을 가질지를 dtype을 통해 지정할 수 있음. 반면 astype은 **이미 지정된 기존 배열의 데이터를 복사**하여, 원하는 데이터 타입으로 변환된 새로운 배열을 생성할 때 사용됨. 

### numpy - boolean & fancy index 
boolean index : numpy 배열은 특정 조건에 따른 값을 배열형태로 추출 할 수 있음 

In [1]:
import numpy as np 

In [5]:
# test_array 배열 생성
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)

# test_array > 3 조건을 적용한 Boolean 배열 생성
condition = test_array > 3
print("test_array > 3:")
print(condition)  # 각 요소가 3보다 큰지 여부를 나타내는 Boolean 배열로 나옴!!!!!!!!!!!!!!!! 
print (condition.astype(np.int32)) # false 0 True 1 로 바꿔줌 

# 조건이 True인 요소만 추출
print("\ntest_array[test_array > 3]:")
print(test_array[test_array > 3])  # 조건에 맞는 요소만 추출

# test_array < 3 조건을 적용한 Boolean 배열 생성
condition = test_array < 3
print("\ntest_array < 3:")
print(condition)  # 각 요소가 3보다 작은지 여부를 나타내는 Boolean 배열

# 조건이 True인 요소만 추출
print("\ntest_array[condition]:")
print(test_array[condition])  # 조건 (3보다 작다) 에 맞는 요소만 추출


test_array > 3:
[False  True False False False  True  True  True]
[0 1 0 0 0 1 1 1]

test_array[test_array > 3]:
[4. 8. 9. 7.]

test_array < 3:
[ True False  True  True False False False False]

test_array[condition]:
[1. 0. 2.]


In [6]:
# 배열 a와 b 생성
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 3, 2], int)  # 반드시 정수형 인덱스 배열이어야 함

# 브라켓 인덱스 방식으로 b의 값을 a의 인덱스로 사용하여 값 추출
result_bracket = a[b]
print("a[b]의 결과 (브라켓 인덱스):")
print(result_bracket)

# Output:
# array([2., 2., 8., 6.])

# take 함수를 사용하여 b의 값을 인덱스로 사용하여 a의 값 추출
result_take = a.take(b)
print("\na.take(b)의 결과 (take 함수):")
print(result_take)

# Output:
# array([2., 2., 8., 6.])


a[b]의 결과 (브라켓 인덱스):
[2. 2. 8. 6.]

a.take(b)의 결과 (take 함수):
[2. 2. 8. 6.]


In [7]:
## 응용편 (vector 뿐만 아니라 matrix 에서도 적용가능)

# 2x2 행렬 a 생성
a = np.array([[1, 4], [9, 16]], float)

# 행 인덱스를 나타내는 배열 b 생성
b = np.array([0, 1, 1, 0], int)  # row 인덱스

# 열 인덱스를 나타내는 배열 c 생성
c = np.array([0, 1, 1, 1], int)  # column 인덱스

# fancy indexing을 사용하여 a[b, c]의 값을 추출
result = a[b, c]
print("a[b, c]의 결과 (fancy indexing):")
print(result)


a[b, c]의 결과 (fancy indexing):
[ 1. 16. 16.  4.]


https://www.youtube.com/watch?v=N4KjOIs-2H8